package app.nzyme.core.timelines;

public enum TimelineEventType {

    MARK,

    DOT11_BSSID_SSID_DIFF,
    DOT11_BSSID_FINGERPRINT_DIFF,
    DOT11_BSSID_STRONGEST_TAP,

    DOT11_SSID_ACTIVE_CHANNEL,
    DOT11_SSID_RATES_DIFF,
    DOT11_SSID_SECURITY_SUITES_DIFF,
    DOT11_SSID_SECURITY_PROTOCOLS_DIFF,
    DOT11_SSID_FINGERPRINTS_DIFF

}
