/*
 *  This file is part of nzyme.
 *
 *  nzyme is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  nzyme is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with nzyme.  If not, see <http://www.gnu.org/licenses/>.
 */

package horse.wtf.nzyme.dot11.anonymization;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;

import java.util.List;

public class RandomSSID {

    // Top SSIDS, from WiGLE Stats: https://www.wigle.net/stats#ssidstats
    public static final List<String> POPULATION = ImmutableList.of(
            "xfinitywifi",
            "XFINITY",
            "BTWiFi-with-FON",
            "linksys",
            "BTWifi-X",
            "AndroidAP",
            "UPC Wi-Free",
            "Ziggo",
            "NETGEAR",
            "Telekom_FON",
            "eduroam",
            "FreeWifi",
            "FreeWifi_secure",
            "optimumwifi",
            "dlink",
            "cablewifi",
            "FRITZ!Box 7490",
            "iPhone",
            "KPN Fon",
            "Virgin media",
            "hpsetup",
            "default",
            "Vodafone Hotspot",
            "TelenetWiFree",
            "asus",
            "orange",
            "SFR WiFi Mobile",
            "TELENETHOMESPOT",
            "BTWIFI",
            "Unitymedia WifiSpot",
            "Vodafone Homespot",
            "Telstra AIR",
            "Guest",
            "Fon WiFi",
            "SFR WiFi FON",
            "TWCWiFi",
            "Home",
            "setup",
            "FRITZ!Box 6490 Cable",
            "vodafone-WiFi",
            "Fritz!Box Fon WLAN 7390",
            "belkin54g",
            "wireless",
            "WLAN",
            "TWCWiFi-Passpoint",
            "BTWi-fi",
            "attwifi",
            "FRITZ!Box 7362 SL",
            "SpectrumWiFi",
            "optimumwifi_Passpoint",
            "portthru",
            "OutOfService",
            "BTOpenzone",
            "PROXIMUS_FON",
            "coxwifi",
            "SpectrumWiFi PluS",
            "internet",
            "FRITZ!Box Fon WLAN 7360",
            "0001softbank",
            "UPC WifiSpots",
            "WOW FI - FASTWEB",
            "BTFON",
            "SWS1day",
            "Darmowe_Orange_WiFi",
            "#NET-CLARO-WIFI",
            "FRITZ!Box 7312",
            "PROXIMUS_AUTO_FON",
            "no_ssid",
            "MEO-WIFI",
            "RedMi",
            "FRITZ!Box Fon WLAN 7270",
            "Tp-link",
            "hhonors",
            "FRITZ!Box Fon WLAN 7170",
            "FRITZ!Box 6360 Cable",
            "KD WLAN Hotspot+",
            "SFR WiFi Public",
            "FON_ZON_FREE_INTERNET",
            "FRITZ!Box Gastzugang",
            "NOS_WIFI_Fon",
            "_AUTO_ONOWiFi",
            "EAGLE",
            "FRITZ!Box 7412",
            "ZyXEL",
            "FRITZ!Box Fon WLAN 7112",
            "wifi",
            "Bouygues Telecom Wi-Fi",
            "Gastzugang",
            "MYChevrolet",
            "walmartwifi",
            "netgear-guest",
            "au_Wi-Fi",
            "FON_BELGACOM",
            "ShawOpen",
            "Wi2premium",
            "ShawMobileHotspot",
            "orange12",
            "BTOpenzone-H",
            "Concrete",
            "Free Public WiFi",
            "FON_FREE_INTERNET",
            "Hilton Honors",
            "VOIP",
            "ASUS_5G",
            "Wi2premium_club",
            "skynet",
            "D-LINK",
            "BTOpenzone-B",
            "0000docomo",
            "Unifi",
            "FON_NETIA_FREE_INTERNET",
            "ACTIONTEC",
            "bandsaw",
            "Proximus Smart Wi-Fi",
            "office",
            "Horizon Wi-Free",
            "PYUR Community",
            "iptime",
            "au_Wi-Fi2",
            "SMC",
            "alticewifi",
            "Telekom",
            "byfly WIFI",
            "FRITZ!Box Fon WLAN 7113",
            "_ONOWiFi",
            "FRITZ!Box 7330 SL",
            "airportthru",
            "freephonie",
            "ShawPasspoint",
            "0002softbank",
            "BELTELECOM WIFI",
            "dd-wrt",
            "U+zone",
            "telecentro WIFI",
            "WiFi-Repeater",
            "MyPlace",
            "NETGEAR_EXT",
            "Motorola",
            "DIR-615",
            "test",
            "demopool1",
            "Marriott_Guest",
            "steel",
            "xerox",
            "OTE WiFi Fon",
            "Sitecom",
            ".FREE_Wi-Fi_PASSPORT",
            "_The Cloud",
            "staff",
            "wlan-ap",
            "7483C2932C56",
            "ollehWiFi",
            "HomeNet",
            "Netcomm Wireless",
            "pretty fly for a wifi",
            "O2 WIFI",
            "Bright House Networks",
            "DIRECT-",
            "0001docomo",
            "guestnet",
            "Target Guest Wi-Fi",
            "My ASUS",
            "Casa",
            "Orange_FunSpot",
            "101",
            "FRITZ!Box WLAN 3170",
            "rebar",
            "DIR-300NRU",
            "FRITZ!Box Fon WLAN 7320",
            "mobile",
            "Telekom Fon",
            "WirelessNet",
            "ATT-WiFi",
            "VOO_HOMESPOT",
            "dge",
            "HTC Portable Hotspot",
            "Voice",
            "FRITZ!Box 7272",
            "FRITZ!Box Fon WLAN 7240",
            "logitecuser",
            "virus",
            "BHN Secure",
            "Dom",
            "demopool2",
            "logitecgameuser",
            "Courtyard_Guest",
            "public",
            "KPN",
            "M4m786iA",
            "Private",
            "@wifi.id",
            "admin",
            "FRITZ!Box WLAN 3270",
            "FRITZ!Box 7330",
            "IPAD",
            "swisscom",
            "FRITZ!Box Fon WLAN 7141",
            "DIR-300",
            "WiFi_OBDii",
            "NETGEAR24",
            "netgear11",
            "MSHOME",
            "NETGEAR22",
            "netgear12",
            "NETGEAR13",
            "NETGEAR23",
            "o2DSL",
            "Netgear88",
            "NETGEAR10",
            "NETGEAR77",
            "Oi WiFi Fon",
            "airport",
            "NETGEAR25",
            "NETGEAR45",
            "Alex",
            "netgear69",
            "NETGEAR01",
            "NETGEAR28",
            "NETGEAR50",
            "NETGEAR75",
            "X03B-89m6274IR",
            "NETGEAR70",
            "NETGEAR41",
            "NETGEAR43",
            "NETGEAR55",
            "Netgear18",
            "NETGEAR47",
            "NETGEAR80",
            "NETGEAR17",
            "NETGEAR40",
            "NETGEAR32",
            "NETGEAR05",
            "netgear44",
            "NETGEAR85",
            "NETGEAR49",
            "NETGEAR51",
            "NETGEAR19",
            "NETGEAR16",
            "NETGEAR21",
            "NETGEAR60",
            "NETGEAR33",
            "NETGEAR35",
            "Netgear09",
            "NETGEAR07",
            "Netgear91",
            "NETGEAR63",
            "NETGEAR81",
            "NETGEAR53",
            "NETGEAR99",
            "Netgear30",
            "NETGEAR48",
            "NETGEAR42",
            "NETGEAR71",
            "NETGEAR74",
            "NETGEAR65",
            "NETGEAR84",
            "Lowes-Guest-WiFi",
            "NETGEAR20",
            "NETGEAR37",
            "Netgear57",
            "netgear76",
            "NETGEAR78",
            "NETGEAR46",
            "NETGEAR73",
            "NETGEAR82",
            "NETGEAR79",
            "netgear27",
            "NETGEAR93",
            "netgear31",
            "NETGEAR64",
            "NETGEAR72",
            "NETGEAR52",
            "NETGEAR14",
            "netgear83",
            "NETGEAR86",
            "NETGEAR38",
            "NETGEAR92",
            "NETGEAR95",
            "NETGEAR67",
            "NETGEAR87",
            "netgear29",
            "NETGEAR15",
            "NETGEAR58",
            "NETGEAR08",
            "NETGEAR97",
            "NETGEAR90",
            "NETGEAR62",
            "Netgear61",
            "NETGEAR26",
            "NETGEAR94",
            "NETGEAR89",
            "netgear54",
            "NETGEAR34",
            "NETGEAR39",
            "NETGEAR66",
            "NETGEAR06",
            "NETGEAR56",
            "NETGEAR04",
            "NETGEAR59",
            "NETGEAR36",
            "NETGEAR96",
            "NETGEAR68",
            "eBOS",
            "NETGEAR03",
            "CMCC",
            "3Com",
            "netgear02",
            "netis",
            "NETGEAR00",
            "NETGEAR98",
            "CHT Wi-Fi(HiNet)",
            "A9F1BDF1DAB1NVT4F4F59",
            "Tele Columbus",
            "Swisscom_Auto_Login",
            "mywifi",
            "McDonalds Free WiFi",
            "Gast",
            "Visitor",
            "FRITZ!Box 6340 Cable",
            "myGMC",
            "CHT Wi-Fi Auto",
            "Sprint Drive",
            "Wi2",
            "tsunami",
            "Draytek",
            "ZTE",
            "TENDA",
            "Neuf WiFi",
            "0",
            "homewifi",
            "TrendNET",
            "Vodafone-Guest",
            "FON_FREE_EAP",
            "Student",
            "FRITZ!Box 3272",
            "FRITZ!Box Fon WLAN 7360 SL",
            "@Hyatt_WiFi",
            "5ECUR3w3p5TOR3",
            "Wi-Fi",
            "Hotspot",
            "YOTA",
            "NetWork",
            "Speedport W 501V",
            "PrettyFlyForAWiFi",
            "Home Network",
            "IHGConnect",
            "WirelessICC",
            "FBI Surveillance Van",
            "mycloud",
            "MySpectrumWiFi80-2G",
            "MySpectrumWiFi88-2G",
            "MySpectrumWiFi78-2G",
            "MySpectrumWiFi58-2G",
            "MySpectrumWiFi30-2G",
            "Carbon",
            "MySpectrumWiFi48-2G",
            "MySpectrumWiFic8-2G",
            "MySpectrumWiFi28-2G",
            "MySpectrumWiFi50-2G",
            "MySpectrumWiFi98-2G",
            "MySpectrumWiFi40-2G",
            "MySpectrumWiFi38-2G",
            "MySpectrumWiFi18-2G",
            "MySpectrumWiFi68-2G",
            "MySpectrumWiFi90-2G",
            "MySpectrumWiFi60-2G",
            "MySpectrumWiFi10-2G",
            "MySpectrumWiFi20-2G",
            "MySpectrumWiFia8-2G",
            "freifunk",
            "MySpectrumWiFi70-2G",
            "MySpectrumWiFi00-2G",
            "Wi2_club",
            "MySpectrumWiFie8-2G",
            "MySpectrumWiFic0-2G",
            "MySpectrumWiFib8-2G",
            "MySpectrumWiFi08-2G",
            "MySpectrumWiFif0-2G",
            "MySpectrumWiFid0-2G",
            "SSID2-2.4",
            "THOMSON",
            "ResidenceInn_GUEST",
            "MySpectrumWiFid8-2G",
            "MySpectrumWiFia0-2G",
            "MySpectrumWiFif8-2G",
            "Wireless-N",
            "MySpectrumWiFie0-2G",
            "MySpectrumWiFib0-2G",
            "Apple",
            "WirelessNet2",
            "cisco",
            "DELTA WifiSpots",
            "myLGNet",
            "govroam",
            "iPhone (2)",
            "RSS-351540",
            "EdiMAX",
            "DIR-620",
            "attwifi - Passpoint",
            "david",
            "Guest Network",
            "UPC Wi-Free #SprawdzUPCMobile!",
            "UBNT",
            "HHT-WM2",
            "Jt9x11w3",
            "HHT-WM1",
            "WirelessSGF",
            "scandic_easy",
            "FRITZ!Box WLAN 3131",
            "dell_device",
            "T wifi zone",
            "Philips WiFi",
            "wirelessmobile",
            "House",
            "SYNC_00000000",
            "Ikea WiFi",
            "LWL-M",
            "HUAWEI p8 lite",
            "Tiscali",
            "tmobile",
            "CORP",
            "alpha",
            "ALICE-WLAN",
            "Maria",
            "eir_WiFi",
            "docomo",
            "mesh",
            "TP-LINK_Extender_2.4GHz",
            "Homenetwork",
            "str241xipv",
            "wificlientesR",
            "serviceswifi",
            "Home1",
            "T wifi zone_secure",
            "GuestWiFi",
            "FRITZ!Box Fon WLAN 7050",
            "optimumwifi-Emergency",
            "COSMOTE WiFi Fon",
            "TCWireless",
            "corporate",
            "LjLr511",
            "FRITZ!Box Fon WLAN 7170 Annex A",
            "Home WiFi",
            "Zoom",
            "Linksys-G",
            "07 Never gonna tell a lie",
            "06 never gonna say goodbye",
            "BYOD",
            "Fon",
            "martin",
            "GDS VCI 01",
            "#TELUS",
            "Connectify-me",
            "yrneh09",
            "Guest_Access",
            "FRITZ!Box WLAN 3370",
            "TP-LINK_Extender",
            "HOL ALU WLAN",
            "_EUSKALTELWIFI_KALEAN",
            "LDSAccess",
            "flashzone-seamless",
            "Proximus Public Wi-Fi",
            "nomad5",
            "ConnectionPoint",
            "XFBSECA7HE6H",
            "Auto-BTWiFi",
            "DSL_2640NRU",
            "Your New Wi-Fi",
            "WWM_P2P",
            "net",
            "NETGEAR-2.4-G",
            "WirelessLocal_IO",
            "CMCC-AUTO",
            "router",
            "NTT-SPOT",
            "myhome",
            "HOL_ZTE_4",
            "NetFasteR IAD 2 (PSTN)",
            "Fairfield_Guest",
            "freebox",
            "Wayport_Access",
            "Guests",
            "ASUS_Guest1",
            "WLAN-TWDC",
            "Mi Phone",
            "INTERSVYAZ_OPEN",
            "ZMD_SAP",
            "0001_Secured_Wi-Fi",
            "swsecure",
            "family",
            "Max",
            "anna",
            "Walmartwifi_2.4",
            "CtLsIiClK",
            "MelitaWiFi",
            "belkin",
            "DIR-320NRU",
            "NETGEAR-5G",
            "FRITZ!Powerline 540E",
            "Matrix",
            "DANIEL",
            "HUAWEI P20 Pro",
            "FRITZ!Box 6320 Cable",
            "Linbury",
            "HomeSweetHome",
            "SMITH",
            "03 Never gonna run around",
            ".1.Free Wi-Fi",
            "IWIFI",
            "cWiFi",
            "02 never gonna let you down",
            "CSL",
            "Green",
            "NETGEAR_Guest1",
            "Telekom Fon WiFi HU",
            "FRITZ!Box 3490",
            "ChinaNet",
            "detnsw",
            "TELE2",
            "DIR-300NRUB7",
            "absauthz",
            "Pod",
            "My Network",
            "NETGEAR1",
            "Johnson",
            "CG-Guest",
            "samsung",
            "Shawgo",
            "mike",
            "thomas",
            "BLUE",
            "USR8054",
            "TG1672G62",
            "FRITZ!Box Fon WLAN 7340",
            "Macysfreewifi",
            "HUAWEI P10",
            "TG1672G22",
            "WirelessLocal",
            "Michael",
            "MySpectrumWiFi88-5G",
            "TG1672GD2",
            "m3connect",
            "TG1672G12",
            "TG1672G92",
            "MySpectrumWiFi90-5G",
            "TG1672G52",
            "MySpectrumWiFi40-5G",
            "MySpectrumWiFi38-5G",
            "maison",
            "TG1672GF2",
            "john",
            "MySpectrumWiFi68-5G",
            "MySpectrumWiFi58-5G",
            "MySpectrumWiFi78-5G",
            "MySpectrumWiFi60-5G",
            "MySpectrumWiFi48-5G",
            "MySpectrumWiFi28-5G",
            "TG1672G32",
            "MySpectrumWiFi30-5G",
            "MySpectrumWiFi50-5G",
            "doma",
            "TG1672G72",
            "MySpectrumWiFi08-5G",
            "MySpectrumWiFi18-5G",
            "MySpectrumWiFic8-5G",
            "MySpectrumWiFi98-5G",
            "MySpectrumWiFi80-5G",
            "MySpectrumWiFi70-5G",
            "TG1672GA2",
            "vpnator",
            "TG1672G82",
            "TG1672G02",
            "TG1672GC2",
            "MySpectrumWiFi10-5G",
            "TG1672GB2",
            "MySpectrumWiFi00-5G",
            "MySpectrumWiFic0-5G",
            "MySpectrumWiFib8-5G",
            "TG1672G42",
            "p2pkoer",
            "MySpectrumWiFi20-5G",
            "TG1672GE2",
            "MySpectrumWiFia8-5G",
            "MySpectrumWiFie0-5G",
            "MySpectrumWiFie8-5G",
            "MySpectrumWiFid0-5G",
            "VW WLAN",
            "MySpectrumWiFib0-5G",
            "MySpectrumWiFia0-5G",
            "MySpectrumWiFid8-5G",
            "Dmpm49Bjfk10",
            "Airlive",
            "MySpectrumWiFif0-5G",
            "Knet",
            "MySpectrumWiFif8-5G",
            "Boingo Hotspot",
            "HomeDepot Public Wi-Fi",
            "Sunshine",
            "PLDTHOMEDSL",
            "HUAWEI P10 lite",
            "Tele2-modem",
            "8===D",
            "Gateway",
            "BATCAVE",
            "Pretty Fly for a Wi-Fi",
            "plusnetwireless",
            "VIVACOM_NET",
            ".wifisfera_telecable",
            "UqtbBHX4Tt",
            "planexuser",
            "chris",
            "DSL-2640U",
            "BETA",
            "laQuinta",
            "TG1672GD2-5G",
            "TG1672G12-5G",
            "Renaissance_GUEST",
            "TG1672G22-5G",
            "george",
            "TG1672G52-5G",
            "Employee",
            "TG1672G72-5G",
            "Apple Store",
            "TG1672G92-5G",
            "TG1672G82-5G",
            "TG1672GA2-5G",
            ".@ AIS SUPER WiFi",
            "TG1672G42-5G",
            "TG1672G62-5G",
            "TG1672GF2-5G",
            "102",
            "MT_free",
            "TG1672GC2-5G",
            "TG1672GB2-5G",
            "TG1672G02-5G",
            "TG1672G32-5G",
            "TG1672GE2-5G",
            "Robert",
            "FBI",
            "WIFI-Guest",
            "brown",
            "ask4 Wireless",
            "_BTWi-fi",
            "Williams",
            "CSL Auto Connect",
            "Bill Wi the Science Fi",
            "AIS SMART Login",
            "vendcust",
            "FRITZ!Box 3390",
            "hol - NetFasteR WLAN 3",
            "Gamma",
            "tKeRl",
            "it hurts when IP",
            "huawei",
            "Angel",
            "Wireless@SG",
            "WebSTAR",
            "backup",
            "DIR-300NRUB6",
            "ANY",
            "InfostradaWiFi",
            "MobileConnect",
            "Wi2eap",
            "ASK4 Wireless (802.1x)",
            "01 Never gonna give you up",
            "FRITZ!Box Fon WLAN 7570 vDSL",
            "#o4D@n!3LS3b@$+1@N<B",
            "ABC",
            "wifi extra",
            ".@  truemoveH",
            "University of Washington",
            "mint",
            ".@  TRUEWIFI",
            "ASDAFreeWifi",
            "Apple Network",
            "VODAFONE_WIFI_108",
            "thuis",
            "Boingo_Wireless",
            "Wireless@SGx",
            "DSLWLANModem200",
            "NETGEAR-5G-GUEST",
            "IBIS",
            "onlime",
            "Speedy Instan@wifi.id",
            "Charlie",
            "XLNBusinessServices",
            "wifi.tattele.com",
            "james",
            "08 and hurt you",
            "Motel 6",
            "demo",
            "MINE",
            "04 and desert you",
            "Marina",
            "Sam",
            "MikroTik",
            "05 Never gonna make you cry",
            "comcast",
            "WiFi-Repeater1",
            "Mywlan",
            "mprotek",
            "HUAWEI P20 lite",
            "wmdemo",
            "home2",
            "HOGWARTS",
            "#NET-WIFI",
            "FON_FREE_ssid",
            "Wireless Network",
            "Guest Wifi",
            "DATA",
            "HOMERUN",
            "elena",
            "SSID",
            "MO1875",
            "Horizon WifiSpots",
            "CVWifi",
            "SKODA_WLAN",
            "Tesco WiFi",
            "MyNet",
            "p27x1c2",
            "APTG Wi-Fi",
            "iot",
            "sca_voice",
            "Orcon-Wireless",
            "DLINK_WIRELESS",
            "make infosec savage again",
            "KaiserGuest",
            "LjLr11",
            "VW_WLAN",
            "HCSC",
            "Nordstrom_Wi-Fi",
            "EMINENT",
            "Free WiFi",
            "eduSTAR",
            "devolo",
            "Silverado",
            "TPLINK",
            "DOM.RU Wi-Fi",
            "sweethome",
            "Living Room",
            "SHC-RF-DS-3",
            "bob",
            "scout",
            "&lt;svg/onload=alert(1)&gt;",
            "FRITZ!Box 6320 v2 Cable",
            "FRITZ!WLAN Repeater 310",
            "Vendor",
            "Pentagram",
            "jones",
            "wireless1",
            "wilson",
            "homebase",
            "Red5",
            "MyNetwork",
            "AlwaysOn",
            "Taco Bell WiFi",
            "TP-LINK_Extender_5GHz",
            "RED",
            "draadloos",
            "PJ-WIRELESS5",
            "NETGEAR-24-G",
            "delta",
            "Miller",
            "HUAWEI P9 lite",
            "9qZNkCYGzf",
            "MO1975",
            "King",
            "FRITZ!Box SL WLAN",
            "AP",
            "Android",
            "olga",
            "swaaa",
            "DG1670A02",
            "secure",
            "t-mobile",
            "Open",
            "meijer-corp",
            "GO1927",
            "FBI Surveillance",
            "Moscow_WiFi_FREE",
            "Buffalo",
            "Peter",
            "guest-wifi",
            "oneteam",
            "Paul",
            "Sweex LW050v2",
            "IHG Connect",
            "NETGEAR50-5G",
            "NETGEAR88-5G",
            "NETGEAR60-5G",
            "My WiFi",
            "Link",
            "FDS020",
            "NETGEAR25-5G",
            "TitEaP21VfS",
            "NETGEAR23-5G",
            "Bella",
            "mark",
            "NETGEAR12-5G",
            "NETGEAR51-5G",
            "NETGEAR69-5G",
            "NETGEAR80-5G",
            "NETGEAR11-5G",
            "NETGEAR63-5G",
            "NETGEAR22-5G",
            "NETGEAR30-5G",
            "NETGEAR86-5G",
            "NETGEAR75-5G",
            "0A344ABB",
            "NETGEAR49-5G",
            "vizio",
            "NETGEAR41-5G",
            "NETGEAR47-5G",
            "Google Starbucks",
            "NETGEAR74-5G",
            "NETGEAR18-5G",
            "NETGEAR52-5G",
            "NETGEAR24-5G",
            "NETGEAR45-5G",
            "NETGEAR53-5G",
            "tardis",
            "NETGEAR97-5G",
            "NETGEAR81-5G",
            "NETGEAR93-5G",
            "NETGEAR62-5G",
            "NETGEAR65-5G",
            "NETGEAR13-5G",
            "NETGEAR58-5G",
            "NETGEAR77-5G",
            "NETGEAR05-5G",
            "NETGEAR84-5G",
            "NETGEAR73-5G",
            "NETGEAR48-5G",
            "NETGEAR72-5G",
            "NETGEAR43-5G",
            "Passpoint Secure",
            "0000_Secured_Wi-Fi",
            "NETGEAR07-5G",
            "Service",
            "NON-RIS-PWL",
            "NETGEAR70-5G",
            "NETGEAR92-5G",
            "NETGEAR83-5G",
            "NETGEAR91-5G",
            "NETGEAR55-5G",
            "NETGEAR35-5G",
            "NETGEAR03-5G",
            "NETGEAR10-5G",
            "NETGEAR06-5G",
            "NETGEAR33-5G",
            "NETGEAR37-5G",
            "NETGEAR85-5G",
            "NETGEAR90-5G",
            "NETGEAR71-5G",
            "NETGEAR57-5G",
            "NETGEAR89-5G",
            "meijer-vendor",
            "NETGEAR20-5G",
            "NETGEAR87-5G",
            "NETGEAR28-5G",
            "NETGEAR79-5G",
            "NETGEAR29-5G",
            "NETGEAR09-5G",
            "NETGEAR16-5G",
            "NETGEAR96-5G",
            "NETGEAR08-5G",
            "NETGEAR56-5G",
            "NETGEAR27-5G",
            "NETGEAR04-5G",
            "conference",
            "NETGEAR21-5G",
            "NETGEAR98-5G",
            "NETGEAR59-5G",
            "NETGEAR31-5G",
            "NETGEAR94-5G",
            "NETGEAR44-5G",
            "NETGEAR17-5G",
            "NETGEAR95-5G",
            "FRITZ!Box",
            "NETGEAR64-5G",
            "NETGEAR40-5G",
            "CFA Private Wi-Fi",
            "NETGEAR39-5G",
            "NETGEAR42-5G",
            "Ambassador_iPad",
            "NETGEAR54-5G",
            "NETGEAR32-5G",
            "NETGEAR15-5G",
            "KEVIN",
            "NETGEAR61-5G",
            "NETGEAR82-5G",
            "NETGEAR78-5G",
            "NETGEAR19-5G",
            "NETGEAR26-5G",
            "NETGEAR99-5G",
            "NETGEAR38-5G",
            "NETGEAR46-5G",
            "DG-Tablet",
            "BLIZZARD",
            "NETGEAR14-5G",
            "DM-HHT",
            "NETGEAR76-5G",
            "NETGEAR68-5G",
            "NETGEAR34-5G",
            "BATMAN",
            "NETGEAR67-5G",
            "Customer ID",
            "NETGEAR02-5G",
            "NETGEAR66-5G",
            "H&M Free WiFi",
            "Sheraton_Guest",
            "TRENDnet652",
            "Radisson_Guest",
            "NETGEAR36-5G",
            "NETGEAR00-5G",
            "TELUS Passpoint",
            "SpeedStream",
            "kiosk",
            "taylor",
            "fritz",
            "Flow Wi-Fi",
            "jackson",
            "Carlos",
            "GABLE",
            "R",
            "NETGEAR01-5G",
            "unknown",
            "DG-Customer",
            "@ AISwifi",
            "DG1670A02-5G",
            "internal",
            "ADSL-WIFI",
            "ICT free WIFI by TRUE",
            "Guest1",
            "anderson",
            "Dynex",
            "Hotel",
            "Inet",
            "123",
            "DG1670AA2",
            "@ 3BB_WiFi",
            "DG1670A22",
            "MOBILE-EAPSIM",
            "Springhill_Guest",
            "20dealer08",
            "DG1670A92",
            "OWNER-PC_Network",
            "Enterprise",
            "SHC-RF-DS-Vendor",
            "Domek",
            "DG1670A82",
            "DG1670A12",
            "1",
            "lee",
            "RegusNETWiFi",
            "DG1670A72",
            "DG1670A62",
            "DG1670A52",
            "MCORP01",
            "DG1670AC2",
            "Virgin Broadband",
            "DG1670AE2",
            "laura",
            "G",
            "DG1670AD2",
            "kabelinternet",
            "Martin Router King",
            "Chromecast",
            "google",
            "DG1670A42",
            "DG1670A32",
            "DG1670AF2",
            "jack",
            "@Home",
            "DigSig",
            "TkLrCp7",
            "steve",
            "@Gap Brands Free Wi-Fi",
            "moevlm05",
            "FRITZ!WLAN Repeater 1750E",
            "PHOENIX",
            "seamless@wifi.id",
            "richard",
            "ibahn",
            "DG1670AB2",
            "Tony",
            "0000FLETS-SPOT",
            "repeater",
            "Quantenna",
            "Invitados",
            "Linda",
            "holidayinn",
            "Frank",
            "POS",
            "VIP",
            "MIGROS WiFi",
            "SST-PR-1",
            "Media",
            "TitWpA23VfS",
            "Hyatt",
            "pegasus",
            "FON_MTS",
            "TRENDnet651",
            "IVAN",
            "HUAWEI Mate 9",
            "ciscosb",
            "Kohls Guest WiFi",
            "Irina",
            "students",
            "Tiger",
            "mary",
            "rose",
            "HUAWEI P20",
            "@ dtac wifi",
            "SHC-RF-ID-2",
            "privat",
            "MERCURY",
            "GovWiFi",
            "Leo",
            "redwood",
            "7357asM",
            "luna",
            "PANERA",
            "orange14",
            "Solar-WiFi",
            "upstairs",
            "getyourownwifi",
            "sandra",
            "DG1670AA2-5G",
            "sage",
            "DG1670A92-5G",
            "ICIDU",
            ".",
            "BTEAM",
            "martinez",
            "CyfrowyPolsat",
            "DIRECT-xyPhilips TV",
            "sasha",
            "DG1670A82-5G",
            "scott",
            "DG-Employee",
            "MetroPCS Portable Mobile Hotspot",
            "DG1670A72-5G",
            "Diana",
            "DG1670A22-5G",
            "DG1670A12-5G",
            "FBI Survailance Van",
            "study",
            "DG1670AE2-5G",
            "DG1670AC2-5G",
            "davis",
            "DG1670AF2-5G",
            "Telekom_SIM",
            "vodafone",
            "Skunk Ass",
            "mycadillac",
            "AirhornAviation",
            "DG1670A32-5G",
            "PGBG00123",
            "DG1670A52-5G",
            "[unknown]",
            "0000FLETS-PORTAL",
            "DG1670A42-5G",
            "MultiNet",
            "TitLeP22VfS",
            "WeWork",
            "DG1670AD2-5G",
            "WeWorkCorp",
            "ShawGuest",
            "mayoguest",
            "Garcia",
            "@ dtac wifi auto",
            "DG1670A62-5G",
            "TSNOfficeWLAN",
            "CMCC-WEB",
            "panda",
            "tom",
            "zb0104p1",
            "Nachowifi",
            "vehicle hotspot",
            "DG1670AB2-5G",
            "FritzBox",
            "TeleCentro Wifi Zone",
            "andy",
            "LISA",
            "BBYDemoFast",
            "studio",
            "EmployeeHotspot",
            "1234",
            ".@ TRUEWIFI",
            "zuhause",
            "WLAN.Tele2.net",
            "wlan1",
            ".@ TrueMove H",
            "HUAWEI P smart",
            "OSUWIRELESS",
            "Home Wireless",
            "Adam",
            "nundsdaten",
            "Andrea",
            "orion",
            "corega",
            "MIT",
            "Aurora",
            "iTaiwan",
            "Oscar",
            "Julia",
            "simon",
            "PRINTER",
            "Beeline_WiFi_WPA",
            "jason",
            "Victoria",
            "Sainsbury's WiFi",
            "ncpsp",
            "Michelle",
            "lausd",
            "a",
            "pocwyg7swean",
            "BION",
            "mcwpa",
            "goesh",
            "VICTOR",
            "PT-WIFI",
            "hp",
            "Living Room TV",
            "lucky",
            "HomeWireless",
            "HUAWEI P8 lite 2017",
            "Fairmont",
            "HUAWEI P9",
            "FBI Van",
            "cobra",
            "NOVOTEL",
            "mario",
            "rodriguez",
            "COLLEAGUE",
            "Jupiter",
            "AirPort Extreme",
            "E9371B78F5",
            "DIRECT-AD-HP PageWide Pro PWA",
            "MERCURE",
            "M",
            "TDPJ",
            "mars",
            "MIOT01",
            "Kelly",
            "zeus",
            "jessica",
            "IBM",
            "wifi1",
            "Home Sweet Home",
            "DV201AM",
            "freeBestBuywifi",
            "Wpa2",
            "fairway",
            "fred",
            "intern",
            "Sca_BoH",
            "philips",
            "wireless2",
            "Work",
            "ATT128",
            "USR5461",
            "AirLink89300",
            "ATT144",
            "MBYOD01",
            "BOLSENA",
            "ATT424",
            "thompson",
            "ATT800",
            "ourhouse",
            "ATT688",
            "equinox",
            "ATT888",
            "LG_Smart_Refrigerator",
            "ATT200",
            "JioPrivateNet",
            "ATT504",
            "ATT256",
            "ATT768",
            "ATT032",
            "ATT824",
            "ATT464",
            "ATT968",
            "ATT400",
            "ATT336",
            "roman",
            "zg0104p1",
            "ATT024",
            "ATT232",
            "ATT280",
            "ATT624",
            "ATT960",
            "ATT936",
            "ATT072",
            "ATT304",
            "ATT320",
            "ATT136",
            "Beeline_WiFi",
            "ATT488",
            "ATT384",
            "nelson",
            "ATT952",
            "ATT216",
            "ATT056",
            "ATT584",
            "ATT344",
            "ssid2",
            "TMOTM",
            "ATT480",
            "ATT104",
            "ATT432",
            "ATT648",
            "ATT872",
            "ATT744",
            "ATT096",
            "ATT408",
            "att296",
            "ATT080",
            "ATT904",
            "xxx",
            "ATT664",
            "Cooper",
            "c2_free",
            "ATT560",
            "ATT120",
            "ATT576",
            "ATT440",
            "att112",
            "1040",
            "att728",
            "ATT472",
            "ATT552",
            "ATT928",
            "ATT808",
            "ATT976",
            "ATT912",
            "ATT840",
            "ATT224",
            "ATT896",
            "ATT240",
            "ATT880",
            "ATT720",
            "ATT176",
            "ATT008",
            "ATT088",
            "ATT208",
            "ATT192",
            "ATT600",
            "ATT920",
            "ATT264",
            "ATT992",
            "ATT776",
            "ATT520",
            "ATT392",
            "ATT376",
            "DRAGON",
            "ATT416",
            "ATT496",
            "ATT288",
            "MGMResorts-WiFi",
            "ATT696",
            "ATT312",
            "att328",
            "freedom",
            "ATT656",
            "ATT160",
            "att360",
            "ATT048",
            "ATT544",
            "ATT168",
            "ATT456",
            "ATT248",
            "private1946",
            "ATT760",
            "ATT528",
            "ATT016",
            "ATT592",
            "ATT512",
            "ATT792",
            "ATT680",
            "ATT816",
            "ATT368",
            "ATT784",
            "ATT848",
            "ATT536",
            "Andrew",
            "BAILEY",
            "ATT736",
            "ATT272",
            "ATT064",
            "ATT616",
            "ATT864",
            "ATT672",
            "SWSGP01",
            "Starbucks WiFi",
            "ATT712",
            "Marriott_Conference",
            "ATT832",
            "ZyXEL NBG-418N v2",
            "ATT856",
            "Mac",
            "ATT944",
            "ATT184",
            "ATT640",
            "ATT632",
            "Y5ZONE",
            "ATT984",
            "ATT752",
            "bacciballum",
            "ATT000",
            "HUAWEI P30 Pro",
            "utexas",
            "ATT608",
            "HAPPY",
            "ATT352",
            "ATT568",
            "ATT152",
            "iPhone (3)",
            "ATT448",
            "WiFi_Aena",
            "linksys1",
            "BUK-Stores",
            "Engenius1",
            "AV",
            "BUK-Corporate",
            "ATT040",
            "ATT704",
            "Loading...",
            "MM",
            "hernandez",
            "Sonos",
            "coco",
            "Dunkin' Donuts Guest",
            "princess",
            "LOCAL1865",
            "OpenWrt",
            "fanTM",
            "PAL3.0",
            "DE-ID01",
            "BUK-Partners",
            "tablet",
            "GVT",
            "Smart",
            "null",
            "LUCY",
            "Lena",
            "INTERMEC",
            "GetYourOwn",
            "WLAN-Guest",
            "HOME-2.4",
            "Maggie",
            "05 Never gonna make you cry_",
            "msvorfuehrung",
            "Bunnings_FreeWiFi",
            "paris",
            "FRITZ!Powerline 546E",
            "P874",
            "Phantom",
            "GuestWireless",
            "subway",
            "Shadow",
            "jose",
            "_XLN Free Wi-Fi",
            "Penthouse",
            "Joe",
            "Alice",
            "Harvard University",
            "meins",
            "awifi",
            "notyourwifi",
            "ALI",
            "Living Room TV.b",
            "0A9988AN",
            "arris54g",
            "apollo",
            "sarah",
            "08  and hurt you",
            "TellMyWifiLoveHer",
            "USER-PC_Network",
            "Rostelecom",
            "DOVADO",
            "Nina",
            "igor",
            "karen",
            "daisy",
            "7SPOT",
            "whopperwifi",
            "dd-wrt_vap",
            "winterfell",
            "AAA",
            "monkey",
            "kubi",
            "WIFI GUEST",
            "m489o5",
            "VerizonWiFiAccess",
            "WaveLAN Network",
            "Towneplace_Guest",
            "Hunter",
            "Panasonic Display1",
            "nacho wifi",
            "Primacom",
            "airlink59300",
            "Andrey",
            "Testing",
            "SSID1",
            "AP0528251901KN1",
            "Shop",
            "Rogers",
            "galaxy",
            "white",
            "3210 Phone WLAN SL",
            "warehouse",
            "5C:D9:98:6C:52:EA",
            "Kim",
            "PLDTMyDSL",
            "rocky",
            "management",
            "HUAWEI Mate 10 Pro",
            "dlink1",
            "NTTWEST-SPOT",
            "CK_Guest",
            "megahoc.v24",
            "HEB Customer WiFi",
            "CenterWIFI",
            "patrick",
            "amanda",
            "asu",
            "Eric",
            "@BayernWLAN",
            "JPMCVisitor",
            "Hello",
            "brian",
            "1030",
            "HUAWEI Mate 10 lite",
            "o2-WLAN03",
            "o2-WLAN11",
            "WLI",
            "R2D2",
            "Alexander",
            "NETGEAR2",
            "LabWLAN",
            "HUAWEI Mate 20 Pro",
            "sara",
            "o2-WLAN08",
            "CFDDATA",
            "RYAN",
            "FREE_U+zone",
            "dave",
            "Patricia",
            "ssid3",
            "BOSS",
            "Speedy",
            "Welcome",
            "za0104p1",
            "mordor",
            "tla73210",
            "Nicole",
            "o2-WLAN06",
            "AndroidTether",
            "o2-WLAN09",
            "william",
            "rfterminal",
            "WMGuest",
            "Wi-Fi Arnet",
            "o2-WLAN04",
            "Print Server",
            "orange13",
            "Edimax AP",
            "homerun1x",
            "Hilton Honors Meeting",
            "MA8EXT001",
            "StudentCom",
            "MAGGIORE",
            "lucas",
            "angela",
            "INTELBRAS",
            "o2-WLAN07",
            "ana",
            "o2-WLAN05",
            "V1500",
            "guest-net",
            "vYou_DDPai_MINI",
            "o2-WLAN01",
            "UHC",
            "pccw",
            "unicorn",
            "GoogleGuest",
            "murphy",
            "beeline-router",
            "henry",
            "P880",
            "o2-WLAN10",
            "o2-WLAN02",
            "WirelessVoice",
            "FRITZ!Box Fon WLAN 7113 Annex A",
            "SWSGUEST01",
            "lighthouse",
            "docomo_eap_roaming",
            "IDEXXw1",
            "DoSPOT-FREE",
            "My Home",
            "GONZALEZ",
            "o2-WLAN00",
            "GuestAccess",
            "CDOBM",
            "OnePlus3",
            "Gabriel",
            "vendorWiFi",
            "appletv",
            "Honor 8",
            "Jordan",
            "DYMOND WR03 2.4G",
            "o2-WLAN54",
            "Harley",
            "eva",
            "Dima",
            "Sunny",
            "Time Capsule",
            "MIT GUEST",
            "Nexus",
            "devices",
            "The Promised LAN",
            "Wifi2",
            "WeWorkGuest",
            "PUBLIX-CUSTOMER",
            "OLIVER",
            "DoSPOT-OWNER",
            "SUPERMAN",
            "DM-FILIALE-PROD",
            "lopez",
            "jennifer",
            "Guest_WIFI",
            "SalesG6",
            "Anygate",
            "rainbow",
            "bruno",
            "Mobility",
            "o2-WLAN80",
            "o2-WLAN18",
            "nick",
            "o2-WLAN47",
            "Google WiFi",
            "o2-WLAN13",
            "o2-WLAN29",
            "o2-WLAN60",
            "o2-WLAN32",
            "M&M",
            "Barbara",
            "gasten",
            "megahoc.v22",
            "o2-WLAN84",
            "o2-WLAN90",
            "IU SECURE",
            "o2-WLAN61",
            "o2-WLAN77",
            "o2-WLAN70",
            "o2-WLAN24",
            "o2-WLAN19",
            "o2-WLAN45",
            "o2-WLAN56",
            "o2-WLAN26",
            "Amped_SR",
            "o2-WLAN21",
            "o2-WLAN82",
            "o2-WLAN28",
            "o2-WLAN76",
            "Vendor_WLAN",
            "master",
            "deathstar",
            "o2-WLAN85",
            "o2-WLAN59",
            "o2-WLAN75",
            "o2-WLAN42",
            "MBRSC01",
            "GROUPEADEO",
            "PetPadParty",
            "GOWIFI",
            "IT",
            "buddy",
            "phwifi",
            "o2-WLAN46",
            "o2-WLAN65",
            "LAUSD-Guest",
            "Sky",
            "Video_Link",
            "Garage",
            "o2-WLAN93",
            "o2-WLAN51",
            "EDUCATION",
            "o2-WLAN16",
            "o2-WLAN81",
            "o2-WLAN44",
            "o2-WLAN87",
            "o2-WLAN74",
            "o2-WLAN62",
            "o2-WLAN15",
            "o2-WLAN37",
            "o2-WLAN23",
            "serenity",
            "o2-WLAN88",
            "o2-WLAN17",
            "HB_INTERNAL",
            "Stella",
            "o2-WLAN12",
            "WEST",
            "o2-WLAN71",
            "o2-WLAN69",
            "o2-WLAN34",
            "o2-WLAN57",
            "o2-WLAN31",
            "o2-WLAN49",
            "o2-WLAN27",
            "o2-WLAN78",
            "o2-WLAN36",
            "o2-WLAN50",
            "o2-WLAN48",
            "o2-WLAN25",
            "Lola",
            "o2-WLAN92",
            "o2-WLAN66",
            "Honor 9",
            "o2-WLAN86",
            "o2-WLAN30",
            "NHS Wi-Fi",
            "HUAWEI P9 lite 2017",
            "o2-WLAN99",
            "o2-WLAN58",
            "o2-WLAN96",
            "o2-WLAN89",
            "o2-WLAN97",
            "megahoc.v29",
            "o2-WLAN14",
            "o2-WLAN68",
            "quality",
            "o2-WLAN53",
            "qwerty",
            "o2-WLAN98",
            "NANCY",
            "Medialink",
            "o2-WLAN35",
            "o2-WLAN22",
            "o2-WLAN20",
            "mimi",
            "A1601",
            "o2-WLAN72",
            "Linksys2",
            "anthony",
            "o2-WLAN43",
            "o2-WLAN38",
            "NETGEAR-DualBand-N",
            "o2-WLAN73",
            "o2-WLAN63",
            "PGBGAN423",
            "o2-WLAN64",
            "SMARTSIGHT",
            "Shangri-La",
            "get your own WiFi",
            "denis",
            "Winternet is Coming",
            "Jerry",
            "o2-WLAN67",
            "o2-WLAN39",
            "o2-WLAN79",
            "o2-WLAN52",
            "o2-WLAN40",
            "UofT",
            "o2-WLAN41",
            "o2-WLAN55",
            "o2-WLAN94",
            "Sandy",
            "o2-WLAN95",
            "o2-WLAN33",
            "FRITZ!Box Fon WLAN",
            "AP1",
            "kmanaged",
            "Paradise",
            "prn",
            "o2-WLAN91",
            "kt_wlan",
            "MARV_WAS_HERE",
            "Sergey",
            "The Lan Before Time",
            "linksys-guest",
            "CORPWIFI",
            "o2-WLAN83",
            "Loves-Services",
            "Dan",
            "grace",
            "NESPOT",
            "ChinaUnicom",
            "Sofia",
            "Free Internet Access",
            "SMU9000",
            "Telia wifi",
            "claudia",
            "HOME-5",
            "Famima_Wi-Fi",
            "SCN",
            "ilaw",
            "lan",
            "Treehouse",
            "NH-Hotel-Group",
            "Antonio",
            "mywireless",
            "Purple",
            "TDLTablet",
            "Home-WiFi",
            "walker",
            "Keenetic",
            "GlobalSuiteWireless",
            "arq_wifi",
            "mmd",
            "MDM",
            "spectra",
            "fourseasons",
            "jeff",
            "bridge",
            "MyFi",
            "saturn",
            "McDonald's FREE WiFi",
            "Tanya",
            "TANetRoaming",
            "SupVen",
            "wifipass",
            "Tina",
            "ACCES G7",
            "E9371B785F",
            "XLNTelecom",
            "tv",
            "moevlm06",
            "Kimpton",
            "MONICA",
            "star",
            "-REWE gratis WLAN-",
            "phone",
            "Ashley",
            "Spectrum",
            "rfcl13ntA",
            "ncpsh",
            "prov.employee",
            "local",
            "asu guest",
            "GN06JXRLG2",
            "Oleg",
            "EMMA",
            "MO3XNO8wm9FRHyjLdRak",
            "Molly",
            "NETGEAR_11ng",
            "owl",
            "Dennis",
            "wlan2",
            "morgan",
            "Natalia",
            "MSI",
            "5F87B1739E",
            "FERNANDO",
            "Harris",
            "Atlantis",
            "NOTYOURS",
            "NetCore",
            "Universities WiFi",
            "searching...",
            "andromeda",
            "UNH-Public",
            "Pandora",
            "D-Link_DIR-600M",
            "Tim",
            "wia001",
            "Family Room TV",
            "alina",
            "AppleWiFi",
            "contextmedia",
            "Stargate",
            "Diamond",
            "sweet home",
            "Training",
            "@VAST",
            "BB",
            "Broadcom",
            "SANCHEZ",
            "guest-access",
            "Fullrate",
            "verizon",
            "UKRTELECOM",
            "hht",
            "CK_Global",
            "felix",
            "myTouch 4G Hotspot",
            "@MWEB FON",
            "ZyXEL_ABGN_1",
            "LevelOne",
            "KT WIFI",
            "b",
            "Jarvis",
            "melissa",
            "+USEN_SPOT_free_s",
            "WIFIMERO",
            "carol",
            "snoopy",
            "c0nnected",
            "Siemenswlan",
            "JWMarriott_GUEST",
            "myhouse",
            "MobileDNET",
            "wca001",
            "xiaomi",
            "Wolf",
            "umd",
            "The Internet",
            "000000",
            "iPet",
            "Telenor",
            "MSFTGUEST",
            "marco",
            "AUDI",
            "Moore",
            "lipari",
            "Westin_GUEST",
            "Wu-Tang LAN",
            "AHSrestrict",
            "Notes",
            "GIGABYTE",
            "It burns when IP",
            "Vesuvius",
            "visitornet",
            "Mgmnt",
            "wia002",
            "Robinson",
            "FRITZ!Box Guest Access",
            "Corpnet",
            "Black",
            "SCA_POS",
            "MIT SECURE",
            "Carmen",
            "wirelesslan",
            "JENNY",
            "ssid4",
            "CTM-WIFI-AUTO",
            "jimmy",
            "MED-105",
            "yournetworkname",
            "Travelodge WiFi",
            "KNS-105",
            "adm",
            "Valhalla",
            "Beeline",
            "tp",
            "temp",
            "zephyros",
            "visitors",
            "royal-wifi",
            "HotelNet",
            "Familia",
            "Solstice",
            "NATASHA",
            "AIR",
            "ben",
            "ArcorWirelessLAN",
            "APHU1",
            "duke",
            "Gold",
            "Area51",
            "Valentina",
            "Production",
            "HTC network",
            "UNH-Secure",
            "Comino",
            "speedywifi",
            "pluto",
            "WholeFoodsMarket",
            "Leon",
            "GUEST_VENDEG",
            "Fibertel WiFi",
            ".@  3BB_WiFi",
            "Telia wifi1x",
            "QEBHW",
            "wlan.stockholm.se",
            "universal",
            "BeBox",
            "TOMMY",
            "StockholmInternt",
            "WirelessDNET",
            "thor",
            "Sophie",
            "cmp-eap",
            "Ghost",
            "[Range] Samsung",
            "helix25",
            "LOVE",
            "innflux",
            "Lugano",
            "BESTBUY",
            "SmartRG7912",
            "TMobileWingman",
            "MySpectrumWiFi44-2G",
            "M2M_IoT",
            "Myresnet",
            "GREGHuKWb9yfG7ahjYCD",
            "paula",
            "Bell",
            "PCCW1x",
            "MySpectrumWiFifc-2G",
            "k",
            "MySpectrumWiFiec-2G",
            "FOX",
            "WIS",
            "Genesis",
            "pedro",
            "MySpectrumWiFi54-2G",
            "MySpectrumWiFi24-2G",
            "Mason",
            "MySpectrumWiFi74-2G",
            "wday",
            "MySpectrumWiFi5c-2G",
            "MySpectrumWiFif4-2G",
            "clark",
            "AMX",
            "MySpectrumWiFi34-2G",
            "Meraki Setup",
            "D-Link_DIR-612",
            "Charles",
            "MobileNet",
            "MySpectrumWiFicc-2G",
            "MySpectrumWiFi04-2G",
            "luis",
            "mobilepoint",
            "NetFasteR IAD (PSTN)",
            "Titan",
            "joseph",
            "MySpectrumWiFi8c-2G",
            "LDC_SAP_Lenovo-PC",
            "MySpectrumWiFi0c-2G",
            "MySpectrumWiFi94-2G",
            "FDS210",
            "MySpectrumWiFic4-2G",
            "MySpectrumWiFi84-2G",
            "MySpectrumWiFi2c-2G",
            "Home_Wifi",
            "kiot",
            "MySpectrumWiFib4-2G",
            "HUAWEI Mate 20 lite",
            "MySpectrumWiFi3c-2G",
            "MySpectrumWiFi9c-2G",
            "PGBG002121A",
            "Parker",
            "MySpectrumWiFi4c-2G",
            "MySpectrumWiFi14-2G",
            "Home-5G",
            "MySpectrumWiFi6c-2G",
            "Untitled",
            "MySpectrumWiFidc-2G",
            "Susan",
            "ALLEN",
            "Lulu",
            "Loves-Employees-WiFi",
            "MySpectrumWiFi1c-2G",
            "MySpectrumWiFiac-2G",
            "HERMES",
            "HOME-Guest",
            "Nokia 3",
            "MT",
            "nighthawk",
            "Diego",
            "s",
            "Lewis",
            "vocera",
            "ShowRoom",
            "MySpectrumWiFi7c-2G",
            "SaskTel Select Wi-Fi 1",
            "ethostream",
            "MySpectrumWiFibc-2G",
            "MySpectrumWiFid4-2G",
            "matt",
            "Guest Access",
            "Exhibitor Internet",
            "12345",
            "pba",
            "FRITZ!Box Fon WLAN 7140 Annex A",
            "MySpectrumWiFi64-2G",
            "777",
            "MySpectrumWiFia4-2G",
            "jorge",
            "Hide Yo Kids Hide Yo Wifi",
            "Huawei AP",
            "LS-Guest",
            "RGIS",
            "MySpectrumWiFie4-2G",
            "GuestDNET",
            "DOCENT",
            "Albert Heijn",
            "WLAN_Markt",
            "leonardo",
            "Harvard Secure",
            "mybuick",
            "NOVA",
            "WLAN01",
            "Danny",
            "Bedroom",
            "Bear",
            "instant",
            "HUAWEI Y6 2018",
            "SNY",
            "Not Yours",
            "StockholmBYOD",
            "Natali",
            "www",
            "NETGEAR_Guest",
            "HUAWEI Y5 2018",
            "Sierra",
            "Jionet",
            "GlobalConnect",
            "omega",
            "hugo",
            "HG520b",
            "uofm",
            "Jesus",
            "linksys_EXT",
            "AU_WiFi",
            "PSU",
            "FBISurveillanceVan",
            "BBUser",
            "Premier Inn Ultimate Wi-Fi",
            "Trinity",
            "Intellinet",
            "mama",
            "Silver",
            "Vanessa",
            "GWireless",
            "utexas-wifi-help",
            "Comfort Inn",
            "Living Room Speaker.o",
            "FordFES-WiFi",
            "young",
            "justin",
            "quality inn",
            "SHC-RF-DS-2",
            "Edge-WP@V2yitry2k#$pth1ngsK&nD",
            "home_network",
            "Bill",
            "T*ni#36!",
            "GUEST@SWN",
            "vera",
            "chen",
            "Anton",
            "00000JAPAN",
            "The Matrix",
            "ricardo",
            "guest.stockholm.se",
            "interwebs",
            "elizabeth",
            "baker",
            "CC",
            "beltelecom",
            "Sharon",
            "DSL-6740C",
            "MySpectrumWiFiba-2G",
            "mustang",
            "jcpGuestWifi",
            "FRITZ!WLAN REPEATER N/G",
            "Subaru Wi-Fi",
            "Abraham Linksys",
            "FRITZ!Powerline 1260E",
            "GuestWLAN",
            "ubcsecure",
            "UCSFwpa",
            "lancom",
            "GuestConnectD",
            "MySpectrumWiFida-2G",
            "LabStation Guest",
            "scanner",
            "events",
            "HARRY",
            "MySpectrumWiFi12-2G",
            "walter",
            "MySpectrumWiFi22-2G",
            "mGuest",
            "StockholmGuest",
            "NSA",
            "AccorHotels-Guests",
            "MySpectrumWiFi82-2G",
            "MySpectrumWiFi32-2G",
            "GoogleWiFi",
            "MySpectrumWiFifa-2G",
            "campbell",
            "honor 6X",
            "stocktaking",
            "MySpectrumWiFiaa-2G",
            "MySpectrumWiFi72-2G",
            "hideyokidshideyowifi",
            "Gary",
            "bslvendor",
            "MySpectrumWiFi8a-2G",
            "Vlad",
            "MySpectrumWiFif2-2G",
            "planexuser-wps",
            "SWN@SSOE",
            "Adams",
            "PDA",
            "MySpectrumWiFi62-2G",
            "MySpectrumWiFi42-2G",
            "MySpectrumWiFi1a-2G",
            "glide",
            "CPS",
            "infinitum movil",
            "HKEdCity",
            "MySpectrumWiFid2-2G",
            "BLUESSO",
            "Guest-Wireless",
            "Sunrise",
            "MySpectrumWiFie2-2G",
            "MySpectrumWiFi2a-2G",
            "colorado",
            "MySpectrumWiFica-2G",
            "marie",
            "Juan",
            "MySpectrumWiFi3a-2G",
            "BSLGUEST",
            "@GoWiFi_Auto",
            "Steven",
            "MySpectrumWiFic2-2G",
            "WONDERLAND",
            "WU TANG LAN",
            "Weefee",
            "MySpectrumWiFi7a-2G",
            "mta-wifi",
            "123456",
            "HOWARD",
            "MySpectrumWiFi92-2G",
            "rjjrjg14",
            "Betty",
            "bslcorp",
            "MySpectrumWiFi4a-2G",
            "MySpectrumWiFi0a-2G",
            "str241xvce",
            "MySpectrumWiFib2-2G",
            "MySpectrumWiFi5a-2G",
            "MySpectrumWiFiea-2G",
            "t",
            "miguel",
            "firefly",
            "andre",
            "cindy",
            "marta",
            "Tele2-2",
            "BezeqFree",
            "188",
            "SURVEY",
            "cookie",
            "Sergio",
            "MySpectrumWiFia2-2G",
            "zebra",
            "MosMetro_Free",
            "Malibu",
            "MySpectrumWiFi02-2G",
            "homer",
            "ADRIAN",
            "MySpectrumWiFi9a-2G",
            "HANDHELDS",
            "ntnuguest",
            "GNet",
            "d",
            "Main",
            "GET YOUR OWN",
            "MySpectrumWiFi6a-2G",
            "Du()]C",
            "ginger",
            "OPPO A3s",
            "Intercontinental",
            "korjubzot",
            "centurylink",
            "J",
            "David's Wi-Fi Network",
            "Private WiFi Default",
            "Robin",
            "PDA-105",
            "MySpectrumWiFi52-2G",
            "jim",
            "Pablo",
            "FRITZ!Box o2 DSL",
            "butterfly",
            "bslrn",
            "alan",
            "KGRUB",
            "CK_MGR",
            "rfoffice",
            "skyfi_secure",
            "TPE-Free",
            "Our house",
            "+USEN_SPOT_free",
            "sammy",
            "wl0_Guest1",
            "Svetlana",
            "Personal",
            "Passpoint Wi-Fi",
            "WWS300",
            "AirLink29150",
            "Netgear123",
            "G604T_WIRELESS",
            "MSFTCORP",
            "Roberto",
            "Sheraton",
            "VodafoneWIFI",
            "HTC",
            "HUAWEI P smart 2019",
            "LCL",
            "Amy",
            "AirNet",
            "Yota Share",
            "@TRUEWIFI",
            "upvel",
            "Castle",
            "AddLee Wi-Fi",
            "megahoc.v25",
            "Sebastian",
            "CORBARA",
            "merlin",
            "TNCAPC5A2BE",
            "EMILY",
            "SMCWBR14S-N4_AP",
            "mitchell",
            "KFC Free WiFi",
            "HG520s",
            "DrayTek-LAN-B",
            "fmc-guest",
            "slate",
            "security",
            "Central",
            "222666328",
            "Roberts",
            "SHWireless4",
            "library",
            "ItHurtsWhenIP",
            "John's Wi-Fi Network",
            "DLinkVWR",
            "00 Axtel WiFi Xtremo",
            "tele2-1",
            "eo",
            "Terry",
            "Roma",
            "redroof",
            "Ramirez",
            "Julie",
            "Perez",
            "UGuest",
            "officedepot",
            "MC",
            "Universities via CSL",
            "Karina",
            "vYou_DDPai_X2Pro",
            "lan1",
            "dlink-guest",
            "boston_bus_600-798",
            "D35Broadband",
            "UQ_Wi-Fi",
            "NEPTUNE",
            "Vika",
            "free",
            "Gizmo",
            "DIR-320",
            "rita",
            "wca002",
            "kitty",
            "Clear",
            "In a day",
            "3HKWi-FiService",
            "HUAWEI P30 lite",
            "jojo",
            "AMREPCR",
            "VIKTOR",
            "FRITZ!Powerline 1240E",
            "spark",
            "I'm to say",
            "ONTelecoms",
            "Salon",
            "-",
            "Momo",
            "eero",
            "OPPO A37f",
            "Stefan",
            "MK",
            "HUAWEI P10 Plus",
            "SUN",
            "HomeOffice",
            "Enroll",
            "Dani",
            "Nastya",
            "Roger",
            "AMD_IBSS",
            "Mobyklick",
            "f@tih",
            "MeijerWiFi",
            "OnePlus 6",
            "cat",
            "Sony",
            "hercules",
            "sfusd-mobi",
            "MICASA",
            "billwithesciencefi",
            "Eduardo",
            "WiFi@DB",
            "Larry",
            "Kroger Guest",
            "WSU Guest",
            "WutangLAN",
            "STORE",
            "JJ",
            "PowerLink_BYOD",
            "DSL-2640R",
            "Ruby",
            "vYou_DDPai_mini2",
            "Michael's Wi-Fi Network",
            "Universities via PCCW",
            "PEANUT",
            "Pavel",
            "Days Inn",
            "sparky",
            "MGMT",
            "stromboli",
            "Not Your WiFi",
            "Nikita",
            "_WiFi-First",
            "BACKOFFICE",
            "TELENETHOTSPOT",
            "CRISTINA",
            "banana",
            "CHASE_GUEST",
            "Rosa",
            "BMW",
            "wifi380A",
            "vladimir",
            "laptop",
            "CMH - Guest",
            "uaguest",
            "venus",
            "ray",
            "WiFly",
            "ResortNet2",
            "Nana",
            "anita",
            "WANG",
            "RUWireless",
            "fmc-nickel",
            "Xy34HH32",
            "daysinn",
            "Premier Inn Free Wi-Fi",
            "dlink_media",
            "nasa",
            "client",
            "carter",
            "sowifi-mesh",
            "jackie",
            "Asgard",
            "BeyondGuestWiFi",
            "ALBERT",
            "TEACHER",
            "Johnny",
            "acasa",
            "Resnet",
            "Network1",
            "Heimnetz",
            "fbox",
            "kristina",
            "UAWiFi",
            "GoldenTree",
            "TalkTalk520",
            "Lobo-Guest",
            "Elvis",
            "amt",
            "SamsClubWiFi",
            "msftwlan",
            "HAL9000",
            "ZIO",
            "dlink2",
            "Menards Private",
            "UCSFguest",
            "Lobo-WiFi",
            "chistandard",
            "TEMP-SUPVEN",
            "UNITE-Staff",
            "timewarnercablewifi",
            "wired",
            "#TELUSDirect",
            "maya",
            "OTE CONNX",
            "Mickey",
            "UNITE-Corporate",
            "iBall-Baton",
            "Iris",
            "Doghouse",
            "ALEXANDRA",
            "MichaelsGuest",
            "bbconnect",
            "016airport",
            "Basement",
            "Christian",
            "dexter",
            "ACE",
            "WORKGROUP",
            "bmobile",
            "Debbie",
            "Airport Express",
            "Tell My WiFi Love Her",
            "adriana",
            "Torres",
            "-Kaufland FreeWiFi-",
            "Daniela",
            "buster",
            "ONE",
            "Ramada",
            "Ken",
            "Dragonfly",
            "Lily",
            "Metro_Free_Wi-Fi",
            "PBC",
            "PANAREA",
            "hopkins",
            "kathy",
            "my_wifi",
            "PTCL-BB",
            "WirelessRDT",
            "Vincent",
            "Instant Internet",
            "SSwifi",
            "catv_Wi-Fi",
            "kk",
            "TECH",
            "barton",
            "Yellow",
            "UofM Secure",
            "gogoinflight",
            "SVETA",
            "Jay",
            "x",
            "SFUSD",
            "HT_AP0",
            "Huawei-Employee",
            "RSN2OfficeWLAN",
            "ccguest",
            "Public WiFi Default",
            "MS",
            "crestron",
            "VIZIO SB3821",
            "AHLAN",
            "Crystal",
            "ARtem",
            "My Place",
            "H",
            "ssw",
            "Speedport Gastzugang",
            "RBCGuest",
            "MYA-L41",
            "stephanie",
            "P2d8T7f2d$",
            "XLN.x",
            "RACHEL",
            "brandon",
            "Holiday Inn",
            "GTvisitor",
            "TWM WiFi (C)",
            "junior",
            "Disney-Guest"
    );

}
